# vi: ft=zsh

# .zshenv: Always sourced

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-${HOME}/.local/state}"

export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

export EDITOR='nvim'

# Homebrew

# https://docs.brew.sh/Installation#post-installation-steps
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
  export HOMEBREW_NO_ENV_HINTS=1
  export HOMEBREW_CASK_OPTS="--appdir=$HOME/Applications"
  path=(
    $(brew --prefix ruby)/bin
    $path
  )
fi

# SDKMAN!

# https://github.com/sdkman/homebrew-tap?tab=readme-ov-file#installation
if [[ -s /opt/homebrew/opt/sdkman-cli/libexec/bin/sdkman-init.sh ]]; then
  export SDKMAN_DIR=$(brew --prefix sdkman-cli)/libexec
  source "${SDKMAN_DIR}/bin/sdkman-init.sh"
fi


# Gradle

export GRADLE_USER_HOME=${XDG_DATA_HOME}/gradle

# Docker

export DOCKER_CONFIG=${XDG_CONFIG_HOME}/docker
